# Default
default:
  just --list

# Build Docker Image
build-image:
  docker build -t techie-lms-app:v1.0.0 . 

# Build Docker Image - Production
build-image-prod:
  docker build --build-arg VITE_API_URL=https://techie-lms-api.miketeddyomondi.dev -t techie-lms-app:v1.0.0 .

# Create docker network
create-net:
  docker network create courses-platform
  
# Run Docker Container
run-container:
  docker run -d -p 5173:3000 --network courses-platform --restart always --name techie-lms-app techie-lms-app:v1.0.0  

# Dispose container  
dispose-container:
  docker stop techie-lms-app
  docker rm techie-lms-app

# Docker compose up (detached)
compose:
  docker compose up -d

# Docker compose down
compose-down:
  docker compose down

# Tear down container plus volumes
tear-down:
  docker compose down -v

# Tag docker image
tag:
  docker tag techie-lms-app:v1.0.0 ranckosolutionsinc/techie-lms-app:v1.0.0

# Push to Docker Hub
push:
  docker push ranckosolutionsinc/techie-lms-app:v1.0.0

